### Get all attendees
GET http://localhost:3000/events

### Get single attendee
GET http://localhost:3000/events/673977a667d3d8b56e2b4b72

### Create new attendee
POST http://localhost:3000/events
Content-Type: application/json

{
  "eventId": "event127",
  "name": "Tech Conference 2024",
  "description": "A conference about the latest in tech.",
  "date": "2024-12-01T10:00:00Z",
  "location": "Convention Center",
  "organizerId": "organizer456",
  "capacity": 500,
  "attendees": [],
  "createdAt": "2024-11-01T12:00:00Z",
  "updatedAt": "2024-11-10T15:00:00Z"
}

### Put method
PUT http://localhost:3000/events/6739777567d3d8b56e2b4b70
Content-Type: application/json

{
  "capacity": 151,
  "location": "Convention Center 18"
}

### Delete method
DELETE http://localhost:3000/events/673977cf67d3d8b56e2b4b73

##################################
##### Get attendees by event #####
##################################
  
### Get event attendees
GET http://localhost:3000/events/673977a667d3d8b56e2b4b72/attendees